# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 410ef4e6474e368b197f2a9aac345716bbcc3d25652275fe10bc61c2980d061bf3294f34f243174a6bdcfc630c9522a33fd62a78dfa3c571a93ee257b783e045

test:
  secret_key_base: 60bd68c4c1504ee7f5bfcb8e3ebdfa2f3cdaafbf62e882f2e9a0ce150a96d9c35e677c0f68671bd42ca282387609deb6cb6dc7be5eb3f5930e007a5d1af25eb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
